### ISSUE TITLE
Uml  Exe

### ISSUE THREAD

**Issue by Elisj52** [Elisj52/SoftModelsHW2_UML#1]

**Comment by robi-y** [comment]
Should I start checking part 1? please assign me..
@Elisj52 @PhillipKatz

**Comment by PhillipKatz** [comment]
Yes. Part 1 is done, and so is part 2.

**Comment by robi-y** [comment]
Hello,
At last some feedback for part1:
Actor table - fine, sometimes we try to identify more abstract or main goal for each actor and stakeholder
Use-case diagram - I only see the xml version (but I could import it to draw.io, so fine), excellent
Detailed use case - format is OK,  I didn't understand fully the main scenario, it looks more like a business scenario rather that a use case showing the interaction with the system.
This is why we have the level field so we know the right level of the use case.

Let's try to document with wiki pages in this course.
אם רוצים להגיב, אפשר גם בעברית אם מעדיפים

**Comment by robi-y** [comment]
Part2 feedback:
- missing main documentation file (readme) - I did not know where to start reading
- So, you chose a different system for this part, OK, but the reader have less context without the UC stage, for example.
- Again, for next time please use markdown instead of office files
- Class diagram: very detailed, but for another system. Nice description
- Activity diagram: fine, but the description does not add much to diagram, and misses design discussion
- Sequence diagram: same
